// This file was autogenerated by lib/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../client/mc/channel.js', ['mc.Channel'], ['goog.asserts', 'goog.debug.Logger', 'goog.events.EventTarget']);
goog.addDependency('../../../client/mc/datasource.js', ['mc.ds'], ['goog.Disposable', 'goog.array', 'goog.asserts', 'goog.async.Delay', 'goog.date', 'goog.date.UtcDateTime', 'goog.debug.Logger', 'goog.events.EventHandler', 'goog.events.EventTarget', 'goog.math', 'goog.object', 'goog.string', 'mc.Channel']);
goog.addDependency('../../../client/mc/gaechannel.js', ['mc.GaeChannel'], ['goog.Uri', 'goog.async.Delay', 'goog.debug.Logger', 'goog.json', 'goog.net.XhrIo', 'goog.object', 'mc.Channel']);
